apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: agente-financeiro
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./k8s/agente-financeiro"
  prune: true
  sourceRef:
    kind: GitRepository
    name: agente-financeiro-repo
  validation: client
