apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: agente-financeiro-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/seuusuario/seurepositorio.git
  ref:
    branch: main
  secretRef:
    name: flux-system
