apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-agente-financeiro
  namespace: agente-financeiro
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.yourdomain.com"
    roleName: "agente-financeiro-role"
    objects: |
      - objectName: "secret/data/agente-financeiro/app"
        secretPath: "secret/data/agente-financeiro/app"
        secretKey: "config"
