version: '3.9'

services:
  app:
    build:
      context: ./infra/docker/app
      dockerfile: Dockerfile
    container_name: agente-app
    ports:
      - "8000:8000"
    volumes:
      - ./infra/docker/app:/app
    networks:
      - agente-net

  nginx:
    build:
      context: ./infra/docker/nginx
      dockerfile: Dockerfile
    container_name: agente-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - agente-net

  mlflow:
    build:
      context: ./infra/docker/mlflow
      dockerfile: Dockerfile
    container_name: agente-mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@postgres:5432/mlflow_db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://mlflow/
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    volumes:
      - ./infra/docker/mlflow:/app
    depends_on:
      - postgres
      - minio
    networks:
      - agente-net

  postgres:
    image: postgres:14
    container_name: agente-postgres
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - agente-net

  minio:
    image: minio/minio
    container_name: agente-minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    networks:
      - agente-net

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/mlflow;
      mc policy set public local/mlflow;
      exit 0;
      "
    networks:
      - agente-net

volumes:
  pgdata:
  minio-data:

networks:
  agente-net:
    driver: bridge
