version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: agente-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - agente-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: agente-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - agente-net

networks:
  agente-net:
    driver: bridge
