---
Organizations:
  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.example.com/msp

Orderer:
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin')"
  Consortium: SampleConsortium

Profiles:
  SampleChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *Orderer
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
    Application:
      Organizations:
        - *Org1