openapi: 3.1.0
info:
  title: Agente Financeiro Contábil - API
  description: API para ingestão de dados, classificação e operações iniciais do Agente Financeiro Contábil.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Ambiente de desenvolvimento local
tags:
  - name: Auth
    description: Endpoints de autenticação
  - name: Dados
    description: Endpoints para ingestão e manipulação de dados
  - name: Classificação
    description: Endpoints da IA classificadora

paths:
  /auth/token:
    post:
      tags:
        - Auth
      summary: Obter token OAuth2 para autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
                  example: "meu-client-id"
                clientSecret:
                  type: string
                  example: "meu-client-secret"
      responses:
        "200":
          description: Token obtido com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
        "401":
          description: Credenciais inválidas

  /dados/upload:
    post:
      tags:
        - Dados
      summary: Enviar arquivo para ingestão e processamento
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Arquivo CSV ou PDF a ser processado
      responses:
        "202":
          description: Arquivo recebido e em processamento
        "400":
          description: Arquivo inválido ou faltando

  /classificacao:
    get:
      tags:
        - Classificação
      summary: Obter status ou resultado da classificação dos dados
      parameters:
        - in: query
          name: batchId
          schema:
            type: string
          required: true
          description: Identificador do lote de dados enviado
      responses:
        "200":
          description: Resultado da classificação
          content:
            application/json:
              schema:
                type: object
                properties:
                  batchId:
                    type: string
                  status:
                    type: string
                    enum: [pending, processing, done, failed]
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        recordId:
                          type: string
                        classification:
                          type: string
                          description: Classe ou categoria definida pela IA
        "404":
          description: Lote não encontrado
